src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $confirm_address = null;

    #[ORM\Column]
    private ?int $postcode = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column]
    private ?string $phone = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[Assert\EqualTo(propertyPath:"email", message: 'emails does not match')]
    public string $email_confirm;

    #[ORM\Column(length: 255)]
    private ?string $town = null;
    #[ORM\Column(length: 255, nullable: true)]
    public ?string $shipping_firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $shipping_lastname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $shipping_address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $shipping_confirm_address = null;

    #[ORM\Column(nullable: true)]
    private ?int $shipping_postcode = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $shipping_country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $shipping_town = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $shipping_phone = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getConfirmAddress(): ?string
    {
        return $this->confirm_address;
    }

    public function setConfirmAddress(string $confirm_address): self
    {
        $this->confirm_address = $confirm_address;

        return $this;
    }

    public function getPostcode(): ?int
    {
        return $this->postcode;
    }

    public function setPostcode(int $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTown(): ?string
    {
        return $this->town;
    }

    public function setTown(string $town): self
    {
        $this->town = $town;

        return $this;
    }

    /**
     * Get the value of email_confirm
     */ 
    public function getEmail_confirm()
    {
        return $this->email_confirm;
    }

    /**
     * Set the value of email_confirm
     *
     * @return  self
     */ 
    public function setEmail_confirm($email_confirm)
    {
        $this->email_confirm = $email_confirm;

        return $this;
    }

    public function setShippingFirstname(?string $shipping_firstname): self
    {
        $this->shipping_firstname = $shipping_firstname;

        return $this;
    }

    public function getShippingLastname(): ?string
    {
        return $this->shipping_lastname;
    }

    public function setShippingLastname(?string $shipping_lastname): self
    {
        $this->shipping_lastname = $shipping_lastname;

        return $this;
    }

    public function getShippingAddress(): ?string
    {
        return $this->shipping_address;
    }

    public function setShippingAddress(?string $shipping_address): self
    {
        $this->shipping_address = $shipping_address;

        return $this;
    }

    public function getShippingConfirmAddress(): ?string
    {
        return $this->shipping_confirm_address;
    }

    public function setShippingConfirmAddress(?string $shipping_confirm_address): self
    {
        $this->shipping_confirm_address = $shipping_confirm_address;

        return $this;
    }

    public function getShippingPostcode(): ?int
    {
        return $this->shipping_postcode;
    }

    public function setShippingPostcode(?int $shipping_postcode): self
    {
        $this->shipping_postcode = $shipping_postcode;

        return $this;
    }

    public function getShippingCountry(): ?string
    {
        return $this->shipping_country;
    }

    public function setShippingCountry(?string $shipping_country): self
    {
        $this->shipping_country = $shipping_country;

        return $this;
    }

    public function getShippingTown(): ?string
    {
        return $this->shipping_town;
    }

    public function setShippingTown(?string $shipping_town): self
    {
        $this->shipping_town = $shipping_town;

        return $this;
    }

    public function getShippingPhone(): ?string
    {
        return $this->shipping_phone;
    }

    public function setShippingPhone(?string $shipping_phone): self
    {
        $this->shipping_phone = $shipping_phone;

        return $this;
    }

    /**
     * Get the value of shipping_firstname
     */ 
    public function getShipping_firstname()
    {
        return $this->shipping_firstname;
    }

    /**
     * Set the value of shipping_firstname
     *
     * @return  self
     */ 
    public function setShipping_firstname($shipping_firstname)
    {
        $this->shipping_firstname = $shipping_firstname;

        return $this;
    } 
}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $payment_method = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\OneToOne(targetEntity: Client::class)]
    #[ORM\JoinColumn(nullable: true)]
    private ?client $client = null;

    #[ORM\ManyToOne(targetEntity: Product::class)]
    #[ORM\JoinColumn(nullable:false, onDelete:"CASCADE")]
    private ?Product $product = null;

    #[ORM\Column]
    private ?int $order_amount = null;

    public function getId(): ?int
    {
        return $this->id;
    }
    public function setId(int $id): ?int
    {
        $this->id = $id;

        return $this->id;
    }
    public function getPaymentMethod(): ?string
    {
        return $this->payment_method;
    }

    public function setPaymentMethod(string $payment_method): self
    {
        $this->payment_method = $payment_method;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getClient(): ?client
    {
        return $this->client;
    }

    public function setClient(client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getProduct(): ?product
    {
        return $this->product;
    }

    public function setProduct(?product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getOrderAmount(): ?int
    {
        return $this->order_amount;
    }

    public function setOrderAmount(int $order_amount): self
    {
        $this->order_amount = $order_amount;

        return $this;
    }
}

src/Controller/LandingPageController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\ClientType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Form;
use Symfony\Component\Form\FormTypeInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Client;
use App\Entity\Product;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use App\Form\GetOrderType;

class LandingPageController extends AbstractController
{

	private $entityManager;
	private HttpClientInterface $httpClientInterface;
	public function __construct(EntityManagerInterface $entityManager, HttpClientInterface $httpClientInterface)
	{

		$this->entityManager = $entityManager;
		$this->httpClientInterface = $httpClientInterface;
	}

	#[Route('/cgv', name: 'cgv')]
	public function afficherCGV(): Response
	{
			return $this->render('landing_page/cgv.html.twig');
	}



    /**
     * @Route("/order/{id}", name="get_order")
     * @throws \Exception
     */
    public function getOrder(Request $request, $id)
    {
        $order = $this->entityManager->getRepository(Order::class)->find($id);

        return $this->render('landing_page/order.html.twig', [
            'order' => $order,
        ]);
    }
    /**
     * @Route("/", name="landing_page")
     * @throws \Exception
     */
    public function index(Request $request): Response
    {
        $products = $this->entityManager->getRepository(Product::class)->findAll();

        $form = $this->createForm(GetOrderType::class);
        $form->handleRequest($request);
        $client = new Client();
        $clientForm = $this->createForm(ClientType::class, $client);
        $clientForm->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())  {

            $data = $form->getData();
            $orderId = $data->getId();

            if (!$orderId) {
                throw $this->createNotFoundException(
                    'La commande n\'existe pas pour l\'ID '.$orderId
                );
            }
            // Redirection vers la route avec l'ID de commande
            return $this->redirectToRoute('get_order', ['id' => $orderId]);
        }

        if ($clientForm->isSubmitted() && $clientForm->isValid()) {
            // Récupération des données du formulaire
            $client = $clientForm->getData();

            // Enregistrement du client dans la base de données
            $this->entityManager->persist($client);
            $this->entityManager->flush();

            $parameters = $request->request->all()['order'];
            $productId = $parameters['cart']['cart_products'][0];
            $paymentMethod = $parameters['payment_method'];

            $zeb = $this->traitement($productId, $paymentMethod, $client);
            $APIOrderId = $zeb['APIOrderId'];
            $order = $zeb['order'];

            return $this->forward(
			'App\Controller\StripeController::prepareCharge',
		    ['order' => $order, 'APIOrder' => $APIOrderId]

		    );





        }

        return $this->render('landing_page/index_new.html.twig', [
            'clientForm' => $clientForm->createView(),
            'form' => $form->createView(),
            'products' => $products,
        ]);
    }

	/**
	 * @Route("/confirmation", name="confirmation")
	 */
	public function confirmation()
	{
		return $this->render('landing_page/confirmation.html.twig', [

		]);
	}

//	#[Route('/traitement', name: 'traitement_commande', methods: "POST, GET")]
	public function traitement(int $ProductId,string $paymentMethod,Client $client )
	{




		$product = $this->entityManager->getRepository(Product::class)->find($ProductId);
		$orderAmount = ($product->getPrice() * (1 - ($product->getSalesPrice() / 100))) / 100;
		$order = new Order();
		$order->setPaymentMethod($paymentMethod);
		$order->setStatus("WAITING");
		$order->setClient($client);
		$order->setProduct($product);
		$order->setOrderAmount($orderAmount);
		$this->entityManager->persist($order);
		$this->entityManager->flush($order);

		$json =
			[
				'order' => [
					'id' => $order->getId(),
					'product' => $order->getProduct()->getName(),
					'payment_method' => $order->getPaymentMethod(),
					'status' => $order->getStatus(),
					'client' => [
						'firstname' => $order->getClient()->getFirstname(),
						'lastname' => $order->getClient()->getLastname(),
						'email' => $order->getClient()->getEmail()
					],
					'addresses' => [
						'billing' => [
							'address_line1' => $order->getClient()->getAddress(),
							'address_line2' => $order->getClient()->getConfirmAddress(),
							'city' => $order->getClient()->getTown(),
							'zipcode' => $order->getClient()->getPostcode(),
							'country' => $order->getClient()->getCountry(),
							'phone' => $order->getClient()->getPhone()
						],
						'shipping' => [
							'address_line1' => $order->getClient()->getAddress(),
							'address_line2' => $order->getClient()->getConfirmAddress(),
							'city' => $order->getClient()->getTown(),
							'zipcode' => $order->getClient()->getPostcode(),
							'country' => $order->getClient()->getCountry(),
							'phone' => $order->getClient()->getPhone()
						]
					]
				]
			];


		$response = $this->httpClientInterface->request(
			'POST',
			'https://api-commerce.simplon-roanne.com/order',
			[
				'headers' => [
					'Content-Type' => 'application/json',
					'accept' => 'application/json',
					'Authorization' => 'Bearer mJxTXVXMfRzLg6ZdhUhM4F6Eutcm1ZiPk4fNmvBMxyNR4ciRsc8v0hOmlzA0vTaX'
				],
				'json' => $json
			]
		);

//		$request = Request::create(
//			$this->generateUrl("app_stripe"),
//			Request::METHOD_POST,
//			['order' => $order]
//		);

        $APIOrderId = json_decode($response->getContent())->order_id;

        $data = [
            'APIOrderId' => $APIOrderId,
            'order' => $order
        ];

        return $data;


//		return $this->forward(
//			'App\Controller\StripeController::prepareCharge',
//			['request' => $request, 'APIOrder' => $APIOrder]
//
//		);
	}
}

templates/landing_page/cgv.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

<!-- Offer Conversion: CurcumaV2 - CPA - [FR] WEB/WAP -->
<iframe src="https://reflexcash.go2cloud.org/aff_l?offer_id=22318" scrolling="no" frameborder="0" width="1"
  height="1"></iframe>
<!-- // End Offer Conversion -->
  <div class="container mx-auto py-8">
    <div class="w-full md:w-2/3 mx-auto">
      <h2 class="text-3xl font-bold mb-6">Conditions Générales de Vente</h2>

      <p>Les présentes Conditions Générales de Vente régissent l'utilisation du Site Internet BattleOffice.com. En utilisant notre site et en passant commande, vous acceptez ces Conditions Générales de Vente et les Conditions d'Utilisation du Site Internet.</p>

      <h3 class="text-2xl font-bold mt-8">1. Informations sur le site</h3>

      <p>BattleOffice.com est un site e-commerce proposant la vente de biens et services pour le jeu. Le site appartient à la société Polo&Reno Corp, SASU au capital social de 10€, immatriculée au RCS de Paris sous le numéro 123456789, et ayant son siège social à Roanne, France.</p>

      <h3 class="text-2xl font-bold mt-8">2. Commandes</h3>

      <p>Les commandes passées sur BattleOffice.com sont soumises à notre acceptation. Nous nous réservons le droit de refuser toute commande pour quelque raison que ce soit, sans préavis.</p>

      <p>Le client est considéré comme ayant passé commande une fois que le règlement a été effectué en totalité et que la confirmation de commande apparaît sur la page de confirmation.</p>

      <h3 class="text-2xl font-bold mt-8">3. Prix</h3>

      <p>Les prix indiqués sur le Site Internet incluent la TVA applicable et sont exprimés en euros. Nous nous réservons le droit de modifier les prix à tout moment, sans préavis. Toutefois, le prix facturé pour une commande sera celui que vous avez accepté au moment de la passation de votre commande.</p>

      <h3 class="text-2xl font-bold mt-8">4. Paiement</h3>

      <p>Les paiements peuvent être effectués par carte bancaire, PayPal ou tout autre moyen de paiement indiqué sur le Site Internet. Les données de paiement sont cryptées pour garantir la sécurité de vos informations.</p>

      <p>Lorsque vous effectuez un paiement, vous garantissez que vous êtes autorisé à utiliser le moyen de paiement utilisé. Nous nous réservons le droit de refuser un paiement ou une commande pour quelque raison que ce soit, sans préavis.</p>

      <h3 class="text-2xl font-bold mt-8">5. Livraison</h3>

      <p>Les délais de livraison indiqués sur le Site Internet sont donnés à titre indicatif. Nous nous efforçons de livrer les commandes dans les délais indiqués, mais nous ne garantissons pas que les délais de livraison seront respectés. Tout retard de livraison n'entraînera pas d'indemnité ou d'annulation de la commande, sauf en cas de force majeure.</p>

      <p>Les frais de livraison sont indiqués lors du processus de commande et peuvent varier en fonction de la destination et du montant de la commande.</p>

      <h3 class="text-2xl font-bold mt-8">6. Droit de rétractation</h3>

      <p>Le client a le droit de se rétracter de son achat dans un délai de 14 jours à compter de la réception de la commande. Les frais de retour sont à la charge du client.</p>

      <p>Les produits retournés doivent être dans leur état d'origine et accompagnés d'une copie de la facture. Nous rembourserons le prix d'achat dans un délai maximum de 14 jours après la réception des produits retournés.</p>

      <h3 class="text-2xl font-bold mt-8">7. Litiges</h3>

      <p>Le présent contrat est soumis au droit français. Tout litige relatif à l'interprétation, l'exécution ou la résiliation du contrat sera soumis à la compétence exclusive des tribunaux compétents.</p>

      <h3 class="text-2xl font-bold mt-8">8. Protection des données</h3>

      <p>Nous veillons à protéger vos données personnelles conformément à notre Politique de Confidentialité. En utilisant notre site, vous acceptez le traitement de vos données personnelles tel que décrit dans cette Politique de Confidentialité.</p>

      <h3 class="text-2xl font-bold mt-8">9. Modification des conditions générales de vente</h3>

      <p>Nous nous réservons le droit de modifier ces Conditions Générales de Vente à tout moment. Vous êtes soumis aux Conditions Générales de Vente en vigueur au moment de votre commande. Toutefois, toute modification des Conditions Générales de Vente ne s'appliquera pas aux commandes que vous avez passées avant la date de modification.</p>
    </div>
  </div>
{% endblock %}

templates/landing_page/confirmation.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

    <!-- Offer Conversion: CurcumaV2 - CPA - [FR] WEB/WAP -->
<iframe src="https://reflexcash.go2cloud.org/aff_l?offer_id=22318" scrolling="no" frameborder="0" width="1" height="1"></iframe>
<!-- // End Offer Conversion -->

<div class="container">
    <div class="container">
        <div class="flash-bar">
            {% for flashMessage in app.flashes('success') %}
                <div class="flash-message flash-success">
                    {{ flashMessage }}
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="content col s12">
            <section class="banner center-align" style="margin: 5rem 0;">
                <h3 class="center-align color_brand_secondary">Merci!<br>Votre commande n° à bien été effectuée</h3>
                <div class="center-align">
                    <h5 class="center-align color_brand_primary">Vérifiez votre boîte de réception,<br>un email vous a été envoyé contenant les informations d'expédition et la facture de votre achat.</h5>
                    <p>Si vous nous n'avez pas reçu cet email vérifiez votre boîte de réception spam ou contactez notre <a href="mailto:contact@battleoffice.com">service consommateur</a>.</p>
                </div>
            </section>
            <section class="banner">
                <div class="row">
                    <div class="col s6 m3">
                        <div class="picto-wrapper center-align valign-wrapper">
                            <img src="assets/images/naturel.png" class="responsive-img" alt="100% naturel">
                            <p class="color_brand_primary">100%<br><b>Ecologique</b></p>
                        </div>
                    </div>
                    <div class="col s6 m3">
                        <div class="picto-wrapper center-align valign-wrapper">
                            <img src="assets/images/secure.png" class="responsive-img" alt="Paiement sécurisé">
                            <p class="color_brand_primary">Paiement<br><b>sécurisé</b></p>
                        </div>
                    </div>
                    <div class="col s6 m3">
                        <div class="picto-wrapper center-align valign-wrapper">
                            <img src="assets/images/chrono.png" class="responsive-img" alt="Votre commande est traitée en moins de 24h">
                            <p class="color_brand_primary">Livraison<br><b>Colis suivi</b></p>
                        </div>
                    </div>
                    <div class="col s6 m3">
                        <div class="picto-wrapper center-align valign-wrapper">
                            <img src="assets/images/like.png" class="responsive-img" alt="Paiement sécurisé">
                            <p class="color_brand_primary">100% Satisfait<br><b>ou remboursé</b></p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
            <section class="banner">
                <div class="center-align">
                    <p>Nous nous engageons à livrer votre commande le plus rapidement possible. Généralement, une commande est traitée en moins de 24h. Vous devez donc ensuite compter le temps de transport jusqu'à la livraison chez vous (généralement entre 24h et 48h). Les commandes passées le vendredi et le week-end sont traitées et expédiées le lundi qui suit.</p>
                    <p>La livraison est offerte pour tous nos clients. Pour toute livraison de produits extérieure à la France métropolitaine, les délais d'acheminement peuvent être légèrement plus importants.</p>
                </div>
            </section>
        </div>
    </div>
</div>
{% endblock %}

templates/landing_page/order.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
{% endblock %}

{% block body %}
<style>
    body {
        overflow-x : hidden;
    }
</style>
    {% if order %}
    <div class="container mt-5 mb-5 overflow-hidden">
        <h1>Order n°{{ order.id }}</h1>
    </div>
    {% else %}
        <div class="container mt-5 mb-5">
            <h1>Order not found</h1>
        </div>
    {% endif %}

    <div class="container mt-5 mb-5">
        <div class="card bg-dark text-white">
            <div class="card-body">
                <h5 class="card-title">Détails de la commande</h5>
                {% if order %}
                    <p class="card-text">Identifiant du produit : {{ order.product.name }}</p>
                    <div class="card" style="width: 120px; height: 120px">
                        <img src="{{ asset('assets/images/') }}/{{ order.product.image }}" alt="{{ order.product.name }}" class="responsive-img">
                    </div>
                    <p class="card-text">Méthode de paiement : {{ order.paymentMethod }}</p>
                    <p class="card-text">Statut : {{ order.status }}</p>
                    <p class="card-text">Montant de la commande : {{ order.orderAmount }}€</p>
                    <p class="card-text">Identifiant du client : {{ order.client.id }}</p>
                    <p class="card-text">Nom du client : {{ order.client.firstname }} {{ order.client.lastname }}</p>
                    <p class="card-text">Date de livraison : 
                        <span id="delivery-date">
                            {% set minDays = "+3 day"|date("U") %}
                            {% set maxDays = "+15 days"|date("U") - minDays %}
                            {% set randomNumber = random(0, maxDays) %}
                            {% set randomDate = minDays + randomNumber %}
                            {{ randomDate|date("d F Y")|replace({
                                "January": "janvier",
                                "February": "février",
                                "March": "mars",
                                "April": "avril",
                                "May": "mai",
                                "June": "juin",
                                "July": "juillet",
                                "August": "août",
                                "September": "septembre",
                                "October": "octobre",
                                "November": "novembre",
                                "December": "décembre"
                            }) }}
                        </span>
                    </p>

                    <table class="striped" style="width: 80%; margin: auto;">
                        <thead>
                            <tr>
                                <th>Adresse de facturation</th>
                                <th>Adresse de livraison</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td style="padding-right: 30px;">
                                    <div class="input-field">
                                        {{order.client.firstname}} {{order.client.lastname}}<br>
                                        {{order.client.address}}<br>
                                        {{ order.client.confirmAddress ?? '' }}<br>
                                        {{order.client.postcode}} {{order.client.town}}<br>
                                        {{order.client.country}}<br>
                                        {{order.client.phone}}<br>
                                    </div>
                                </td>
                                <td style="padding-left: 30px;">
                                    <div class="input-field">
                                        {% if order.client.shipping_firstname is defined and order.client.shipping_firstname %}
                                        
                                        {{order.client.shipping_firstname}} {{order.client.shippingLastname}}<br>
                                        {{order.client.shippingAddress}}<br>
                                        {{ order.client.shippingConfirmAddress ?? '' }}<br>
                                        {{order.client.shippingPostcode}} {{order.client.shippingTown}}<br>
                                        {{order.client.shippingCountry}}<br>
                                        {{order.client.shippingPhone}}<br>

                                        {% else %}

                                        {{order.client.firstname}} {{order.client.lastname}}<br>
                                        {{order.client.address}}<br>
                                        {{ order.client.confirmAddress ?? '' }}<br>
                                        {{order.client.postcode}} {{order.client.town}}<br>
                                        {{order.client.country}}<br>
                                        {{order.client.phone}}<br>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                {% else %}
                    <p class="card-text">Aucune commande trouvée</p>
                {% endif %}
            </div>
        </div>
    </div>




{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
{% endblock %}